### ISSUE TITLE
Повторное взятие книги пользователем и оценка

### ISSUE THREAD

**Issue by strwatcher** [FarPostBooks/farpostbooks_frontend#13]
Как будем действовать при возврате книги после повторного взятия?

- Каждый раз требовать выставлять рейтинг у книги
- Выставлять рейтинг только после первого возварта
- Дать возможность поменять рейтинг после возврата
- Сделать рейтинг необязательным и отделить выставление книги от ее возврата

**Comment by Faner201** [comment]
4 сразу нет, так как нам обязательно выставлять рейтинг после возврата
2 и 3 выглядят хорошо 
1 выглядит очень сомнительно, смысл заставлять человека каждый раз это выставлять то

**Comment by strwatcher** [comment]
С точки зрения реализации 2 проще

**Comment by KatantDev** [comment]
С точки зрения нашего интерфейса логичнее всего первый вариант. 
- Если мы обновляем рейтинг во всех строчках, то надо менять везде, а если в первый раз книга понравилась, а второй нет или наоборот. Как быть?
- Выставлять рейтинг только после первого возврата очень сомнительно, также как и 4 пункт (рейтинг обязателен для выставления), а тянуть рейтинг поставленный в первый раз - глупо, первый раз книга понравилась, а при повторном прочтении - нет.

**Comment by strwatcher** [comment]
Берем 1 вариант
