### ISSUE TITLE
Реализовать систему рейтинга книг

### ISSUE THREAD

**Issue by KatantDev** [FarPostBooks/farpostbooks_frontend#9]
- При возврате книги меню для выставления рейтинга от 1 до 5
- В таблице с информацией о книге добавить пункт рейтинг возле каждой строки для отображения оценки, оставленной пользователем при возвращении
- Возможно реализовать систему средней оценки книги, если это не сильно долго. Есть возможность добавить отдельное поле при ответе API, если требуется

**Comment by strwatcher** [comment]
Средний рейтинг долго слишком, кмк.
Если завтра будет желание и время, то можно
